GET_MACHINES_DATA = [
    {
        "id": 379,
        "name": "Stacked",
        "os": "Linux",
        "points": 50,
        "static_points": 50,
        "release": "2021-09-18T16:00:00.000000Z",
        "user_owns_count": 295,
        "root_owns_count": 234,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "4.1",
        "difficulty": 68,
        "feedbackForChart": {
            "counterCake": 13,
            "counterVeryEasy": 1,
            "counterEasy": 3,
            "counterTooEasy": 16,
            "counterMedium": 66,
            "counterBitHard": 41,
            "counterHard": 76,
            "counterTooHard": 64,
            "counterExHard": 29,
            "counterBrainFuck": 36,
        },
        "avatar": "/storage/avatars/51b47673a71a7f2d0c2fba0d9392cc83.png",
        "difficultyText": "Insane",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 114053,
            "name": "TheCyberGeek",
            "avatar": "/storage/avatars/91366fea811206f5437c9a9df4d6a68e.png",
            "isRespected": True,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.112",
    },
    {
        "id": 388,
        "name": "Hancliffe",
        "os": "Windows",
        "points": 40,
        "static_points": 40,
        "release": "2021-10-09T16:00:00.000000Z",
        "user_owns_count": 579,
        "root_owns_count": 346,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "4.5",
        "difficulty": 64,
        "feedbackForChart": {
            "counterCake": 22,
            "counterVeryEasy": 4,
            "counterEasy": 16,
            "counterTooEasy": 33,
            "counterMedium": 123,
            "counterBitHard": 113,
            "counterHard": 156,
            "counterTooHard": 105,
            "counterExHard": 31,
            "counterBrainFuck": 47,
        },
        "avatar": "/storage/avatars/16b1e2f11b9c6b1afd80078c6c141bf8.png",
        "difficultyText": "Hard",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 189435,
            "name": "Revolt",
            "avatar": "/storage/avatars/5bdea988bf18ecab359a500859425533.png",
            "isRespected": False,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.115",
    },
    {
        "id": 398,
        "name": "Devzat",
        "os": "Linux",
        "points": 30,
        "static_points": 30,
        "release": "2021-10-16T16:00:00.000000Z",
        "user_owns_count": 3360,
        "root_owns_count": 3176,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "4.6",
        "difficulty": 50,
        "feedbackForChart": {
            "counterCake": 104,
            "counterVeryEasy": 93,
            "counterEasy": 321,
            "counterTooEasy": 590,
            "counterMedium": 1380,
            "counterBitHard": 552,
            "counterHard": 291,
            "counterTooHard": 99,
            "counterExHard": 33,
            "counterBrainFuck": 45,
        },
        "avatar": "/storage/avatars/43a4b7b2ba6e11c48b128aa46cddaf49.png",
        "difficultyText": "Medium",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 34604,
            "name": "c1sc0",
            "avatar": "/storage/avatars/2e089ee8850cadf640a67c115af03634.png",
            "isRespected": False,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.118",
    },
    {
        "id": 399,
        "name": "Overflow",
        "os": "Linux",
        "points": 40,
        "static_points": 40,
        "release": "2021-10-23T16:00:00.000000Z",
        "user_owns_count": 535,
        "root_owns_count": 467,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "4.7",
        "difficulty": 62,
        "feedbackForChart": {
            "counterCake": 16,
            "counterVeryEasy": 1,
            "counterEasy": 15,
            "counterTooEasy": 38,
            "counterMedium": 149,
            "counterBitHard": 110,
            "counterHard": 175,
            "counterTooHard": 72,
            "counterExHard": 20,
            "counterBrainFuck": 25,
        },
        "avatar": "/storage/avatars/7336681a317f62ac672ee6f5b0982db4.png",
        "difficultyText": "Hard",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 172213,
            "name": "Xclow3n",
            "avatar": "/storage/avatars/fab93c4cb7cddfc03e460d81efaaf05a.png",
            "isRespected": False,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.119",
    },
    {
        "id": 408,
        "name": "Secret",
        "os": "Linux",
        "points": 20,
        "static_points": 20,
        "release": "2021-10-30T16:00:00.000000Z",
        "user_owns_count": 8107,
        "root_owns_count": 6991,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "4.2",
        "difficulty": 44,
        "feedbackForChart": {
            "counterCake": 314,
            "counterVeryEasy": 625,
            "counterEasy": 1800,
            "counterTooEasy": 1854,
            "counterMedium": 1966,
            "counterBitHard": 808,
            "counterHard": 594,
            "counterTooHard": 202,
            "counterExHard": 71,
            "counterBrainFuck": 136,
        },
        "avatar": "/storage/avatars/c05aacfbe9bd98ea2840070538283b1e.png",
        "difficultyText": "Easy",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 485024,
            "name": "z9fr",
            "avatar": "/storage/avatars/5015baaf9b4c50a5728666ebf49f7abe.png",
            "isRespected": False,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.120",
    },
    {
        "id": 409,
        "name": "Toby",
        "os": "Linux",
        "points": 50,
        "static_points": 50,
        "release": "2021-11-06T17:00:00.000000Z",
        "user_owns_count": 273,
        "root_owns_count": 263,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "2.9",
        "difficulty": 74,
        "feedbackForChart": {
            "counterCake": 17,
            "counterVeryEasy": 3,
            "counterEasy": 5,
            "counterTooEasy": 10,
            "counterMedium": 51,
            "counterBitHard": 15,
            "counterHard": 41,
            "counterTooHard": 68,
            "counterExHard": 83,
            "counterBrainFuck": 67,
        },
        "avatar": "/storage/avatars/17b71361b8a8b36cd958307fc99d2a93.png",
        "difficultyText": "Insane",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 52045,
            "name": "InfoSecJack",
            "avatar": "/storage/avatars/8923cce8adc04104a0f0c777a88b9cf4.png",
            "isRespected": False,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.121",
    },
    {
        "id": 410,
        "name": "Shibboleth",
        "os": "Linux",
        "points": 30,
        "static_points": 30,
        "release": "2021-11-13T17:00:00.000000Z",
        "user_owns_count": 2993,
        "root_owns_count": 2793,
        "authUserInUserOwns": None,
        "authUserInRootOwns": None,
        "isTodo": True,
        "authUserHasReviewed": False,
        "stars": "4.7",
        "difficulty": 49,
        "feedbackForChart": {
            "counterCake": 69,
            "counterVeryEasy": 77,
            "counterEasy": 296,
            "counterTooEasy": 624,
            "counterMedium": 1186,
            "counterBitHard": 467,
            "counterHard": 228,
            "counterTooHard": 76,
            "counterExHard": 21,
            "counterBrainFuck": 43,
        },
        "avatar": "/storage/avatars/100cfb88684a919c9915ca102378f6ee.png",
        "difficultyText": "Medium",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 8930,
            "name": "knightmare",
            "avatar": "/storage/avatars/80489bf83883d6ea1a35b754685886bb.png",
            "isRespected": False,
        },
        "maker2": {
            "id": 2984,
            "name": "mrb3n",
            "avatar": "/storage/avatars/179203847493c31adff2afdb510b3025.png",
            "isRespected": False,
        },
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.124",
    },
    {
        "id": 415,
        "name": "Unicode",
        "os": "Linux",
        "points": 30,
        "static_points": 30,
        "release": "2021-11-27T17:00:00.000000Z",
        "user_owns_count": 1729,
        "root_owns_count": 1646,
        "authUserInUserOwns": None,
        "authUserInRootOwns": None,
        "isTodo": True,
        "authUserHasReviewed": False,
        "stars": "4.0",
        "difficulty": 53,
        "feedbackForChart": {
            "counterCake": 50,
            "counterVeryEasy": 35,
            "counterEasy": 106,
            "counterTooEasy": 233,
            "counterMedium": 701,
            "counterBitHard": 344,
            "counterHard": 220,
            "counterTooHard": 83,
            "counterExHard": 21,
            "counterBrainFuck": 39,
        },
        "avatar": "/storage/avatars/8d3e1b5419f74d6ae4c1ac7f2faf949f.png",
        "difficultyText": "Medium",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 137089,
            "name": "wh0am1root",
            "avatar": "/storage/avatars/b8a6a97709b97241077bf3a20e4c1563.png",
            "isRespected": False,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.126",
    },
    {
        "id": 416,
        "name": "Backdoor",
        "os": "Linux",
        "points": 20,
        "static_points": 20,
        "release": "2021-11-20T17:00:00.000000Z",
        "user_owns_count": 7605,
        "root_owns_count": 7204,
        "authUserInUserOwns": None,
        "authUserInRootOwns": None,
        "isTodo": True,
        "authUserHasReviewed": False,
        "stars": "3.6",
        "difficulty": 43,
        "feedbackForChart": {
            "counterCake": 372,
            "counterVeryEasy": 559,
            "counterEasy": 1521,
            "counterTooEasy": 1871,
            "counterMedium": 2010,
            "counterBitHard": 746,
            "counterHard": 456,
            "counterTooHard": 147,
            "counterExHard": 39,
            "counterBrainFuck": 101,
        },
        "avatar": "/storage/avatars/085b46bff51d7bc49ec1ddb6ba8a3d36.png",
        "difficultyText": "Easy",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 79623,
            "name": "hkabubaker17",
            "avatar": "/storage/avatars/c5bffe7b6b184a8e449012e1335f9ea2.png",
            "isRespected": False,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.125",
    },
    {
        "id": 417,
        "name": "Fingerprint",
        "os": "Linux",
        "points": 50,
        "static_points": 50,
        "release": "2021-12-04T17:00:00.000000Z",
        "user_owns_count": 164,
        "root_owns_count": 160,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "3.5",
        "difficulty": 76,
        "feedbackForChart": {
            "counterCake": 11,
            "counterVeryEasy": 3,
            "counterEasy": 2,
            "counterTooEasy": 4,
            "counterMedium": 27,
            "counterBitHard": 7,
            "counterHard": 24,
            "counterTooHard": 40,
            "counterExHard": 46,
            "counterBrainFuck": 56,
        },
        "avatar": "/storage/avatars/391398eafb85e0f3a85173097218f68e.png",
        "difficultyText": "Insane",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 476556,
            "name": "irogir",
            "avatar": "/storage/avatars/6f0ae07db6e33c60145bfdccb66aa4d7.png",
            "isRespected": False,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.127",
    },
    {
        "id": 421,
        "name": "Timing",
        "os": "Linux",
        "points": 30,
        "static_points": 30,
        "release": "2021-12-11T17:00:00.000000Z",
        "user_owns_count": 1492,
        "root_owns_count": 1371,
        "authUserInUserOwns": None,
        "authUserInRootOwns": None,
        "isTodo": True,
        "authUserHasReviewed": False,
        "stars": "4.4",
        "difficulty": 55,
        "feedbackForChart": {
            "counterCake": 39,
            "counterVeryEasy": 21,
            "counterEasy": 81,
            "counterTooEasy": 191,
            "counterMedium": 539,
            "counterBitHard": 335,
            "counterHard": 234,
            "counterTooHard": 87,
            "counterExHard": 29,
            "counterBrainFuck": 42,
        },
        "avatar": "/storage/avatars/97e14470934b37a7c70f68345f4cc51f.png",
        "difficultyText": "Medium",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 476556,
            "name": "irogir",
            "avatar": "/storage/avatars/6f0ae07db6e33c60145bfdccb66aa4d7.png",
            "isRespected": False,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.135",
    },
    {
        "id": 422,
        "name": "Search",
        "os": "Windows",
        "points": 40,
        "static_points": 40,
        "release": "2021-12-18T17:00:00.000000Z",
        "user_owns_count": 762,
        "root_owns_count": 682,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "4.8",
        "difficulty": 59,
        "feedbackForChart": {
            "counterCake": 19,
            "counterVeryEasy": 8,
            "counterEasy": 31,
            "counterTooEasy": 77,
            "counterMedium": 242,
            "counterBitHard": 166,
            "counterHard": 189,
            "counterTooHard": 88,
            "counterExHard": 29,
            "counterBrainFuck": 29,
        },
        "avatar": "/storage/avatars/03cea0fc2ebc50151c0dfa9e375e3ded.png",
        "difficultyText": "Hard",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 610173,
            "name": "dmw0ng",
            "avatar": "/storage/avatars/629da08cdd36bcee3a3ae1506e88b41d.png",
            "isRespected": False,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.129",
    },
    {
        "id": 423,
        "name": "Pandora",
        "os": "Linux",
        "points": 20,
        "static_points": 20,
        "release": "2022-01-08T17:00:00.000000Z",
        "user_owns_count": 4137,
        "root_owns_count": 3785,
        "authUserInUserOwns": None,
        "authUserInRootOwns": None,
        "isTodo": True,
        "authUserHasReviewed": False,
        "stars": "4.5",
        "difficulty": 48,
        "feedbackForChart": {
            "counterCake": 182,
            "counterVeryEasy": 203,
            "counterEasy": 544,
            "counterTooEasy": 756,
            "counterMedium": 1211,
            "counterBitHard": 612,
            "counterHard": 414,
            "counterTooHard": 125,
            "counterExHard": 49,
            "counterBrainFuck": 89,
        },
        "avatar": "/storage/avatars/6ac0e76002774bbfac92b0dbc86cb6af.png",
        "difficultyText": "Easy",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 114053,
            "name": "TheCyberGeek",
            "avatar": "/storage/avatars/91366fea811206f5437c9a9df4d6a68e.png",
            "isRespected": True,
        },
        "maker2": {
            "id": 610173,
            "name": "dmw0ng",
            "avatar": "/storage/avatars/629da08cdd36bcee3a3ae1506e88b41d.png",
            "isRespected": False,
        },
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.136",
    },
    {
        "id": 427,
        "name": "AdmirerToo",
        "os": "Linux",
        "points": 40,
        "static_points": 40,
        "release": "2022-01-15T17:00:00.000000Z",
        "user_owns_count": 539,
        "root_owns_count": 405,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": True,
        "stars": "4.1",
        "difficulty": 63,
        "feedbackForChart": {
            "counterCake": 22,
            "counterVeryEasy": 3,
            "counterEasy": 14,
            "counterTooEasy": 32,
            "counterMedium": 139,
            "counterBitHard": 80,
            "counterHard": 128,
            "counterTooHard": 83,
            "counterExHard": 29,
            "counterBrainFuck": 38,
        },
        "avatar": "/storage/avatars/6ac5a30fba95dc8d852a357438b39fe8.png",
        "difficultyText": "Hard",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 159204,
            "name": "polarbearer",
            "avatar": "/storage/avatars/42e4ddecf8e7bf17fba4f3904cd8d441.png",
            "isRespected": False,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.137",
    },
    {
        "id": 429,
        "name": "Meta",
        "os": "Linux",
        "points": 30,
        "static_points": 30,
        "release": "2022-01-22T17:00:00.000000Z",
        "user_owns_count": 2088,
        "root_owns_count": 2000,
        "authUserInUserOwns": None,
        "authUserInRootOwns": None,
        "isTodo": True,
        "authUserHasReviewed": False,
        "stars": "4.6",
        "difficulty": 49,
        "feedbackForChart": {
            "counterCake": 39,
            "counterVeryEasy": 69,
            "counterEasy": 203,
            "counterTooEasy": 333,
            "counterMedium": 724,
            "counterBitHard": 292,
            "counterHard": 156,
            "counterTooHard": 43,
            "counterExHard": 8,
            "counterBrainFuck": 34,
        },
        "avatar": "/storage/avatars/f5531447128def5b8c4398d0cc2a14cf.png",
        "difficultyText": "Medium",
        "playInfo": {
            "isSpawned": True,
            "isSpawning": None,
            "isActive": False,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 27582,
            "name": "Nauten",
            "avatar": "/storage/avatars/897a8ea490ed626be1107bb8f70daac2.png",
            "isRespected": False,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.140",
    },
    {
        "id": 431,
        "name": "Scanned",
        "os": "Linux",
        "points": 50,
        "static_points": 50,
        "release": "2022-01-29T17:00:00.000000Z",
        "user_owns_count": 72,
        "root_owns_count": 50,
        "authUserInUserOwns": None,
        "authUserInRootOwns": None,
        "isTodo": True,
        "authUserHasReviewed": False,
        "stars": "5.0",
        "difficulty": 77,
        "feedbackForChart": {
            "counterCake": 4,
            "counterVeryEasy": 1,
            "counterEasy": 1,
            "counterTooEasy": 2,
            "counterMedium": 5,
            "counterBitHard": 3,
            "counterHard": 14,
            "counterTooHard": 11,
            "counterExHard": 9,
            "counterBrainFuck": 26,
        },
        "avatar": "/storage/avatars/a2ef7591f20178d80da6c2522ba82b49.png",
        "difficultyText": "Insane",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 83743,
            "name": "clubby789",
            "avatar": "/storage/avatars/571a1cebb38673df9a38f5fd5ede9276.png",
            "isRespected": False,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.141",
    },
    {
        "id": 432,
        "name": "Paper",
        "os": "Linux",
        "points": 20,
        "static_points": 20,
        "release": "2022-02-05T17:00:00.000000Z",
        "user_owns_count": 4864,
        "root_owns_count": 4344,
        "authUserInUserOwns": None,
        "authUserInRootOwns": None,
        "isTodo": True,
        "authUserHasReviewed": False,
        "stars": "4.5",
        "difficulty": 39,
        "feedbackForChart": {
            "counterCake": 253,
            "counterVeryEasy": 426,
            "counterEasy": 1302,
            "counterTooEasy": 1149,
            "counterMedium": 889,
            "counterBitHard": 252,
            "counterHard": 141,
            "counterTooHard": 45,
            "counterExHard": 13,
            "counterBrainFuck": 41,
        },
        "avatar": "/storage/avatars/eb4e685c033d8af0b8cc00446f295f9d.png",
        "difficultyText": "Easy",
        "playInfo": {
            "isSpawned": True,
            "isSpawning": None,
            "isActive": False,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 92926,
            "name": "secnigma",
            "avatar": "/storage/avatars/fc1c35025aa7babcc86031b99f36360a.png",
            "isRespected": False,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.143",
    },
    {
        "id": 438,
        "name": "Acute",
        "os": "Windows",
        "points": 40,
        "static_points": 40,
        "release": "2022-02-12T17:00:00.000000Z",
        "user_owns_count": 298,
        "root_owns_count": 252,
        "authUserInUserOwns": None,
        "authUserInRootOwns": None,
        "isTodo": True,
        "authUserHasReviewed": False,
        "stars": "4.6",
        "difficulty": 63,
        "feedbackForChart": {
            "counterCake": 8,
            "counterVeryEasy": 2,
            "counterEasy": 3,
            "counterTooEasy": 12,
            "counterMedium": 71,
            "counterBitHard": 53,
            "counterHard": 77,
            "counterTooHard": 36,
            "counterExHard": 12,
            "counterBrainFuck": 16,
        },
        "avatar": "/storage/avatars/84ab22908d5dd51ab6bd64f99f81b7be.png",
        "difficultyText": "Hard",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 610173,
            "name": "dmw0ng",
            "avatar": "/storage/avatars/629da08cdd36bcee3a3ae1506e88b41d.png",
            "isRespected": False,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.145",
    },
    {
        "id": 439,
        "name": "Undetected",
        "os": "Linux",
        "points": 30,
        "static_points": 30,
        "release": "2022-02-19T17:00:00.000000Z",
        "user_owns_count": 842,
        "root_owns_count": 571,
        "authUserInUserOwns": None,
        "authUserInRootOwns": None,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "3.5",
        "difficulty": 52,
        "feedbackForChart": {
            "counterCake": 19,
            "counterVeryEasy": 13,
            "counterEasy": 56,
            "counterTooEasy": 83,
            "counterMedium": 207,
            "counterBitHard": 72,
            "counterHard": 53,
            "counterTooHard": 23,
            "counterExHard": 19,
            "counterBrainFuck": 17,
        },
        "avatar": "/storage/avatars/642db092f1e18466871db9f12933396f.png",
        "difficultyText": "Medium",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 114053,
            "name": "TheCyberGeek",
            "avatar": "/storage/avatars/91366fea811206f5437c9a9df4d6a68e.png",
            "isRespected": True,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.146",
    },
    {
        "id": 444,
        "name": "RouterSpace",
        "os": "Linux",
        "points": 20,
        "static_points": 20,
        "release": "2022-02-26T17:00:00.000000Z",
        "user_owns_count": 239,
        "root_owns_count": 190,
        "authUserInUserOwns": None,
        "authUserInRootOwns": None,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "2.8",
        "difficulty": 37,
        "feedbackForChart": {
            "counterCake": 11,
            "counterVeryEasy": 12,
            "counterEasy": 10,
            "counterTooEasy": 14,
            "counterMedium": 19,
            "counterBitHard": 2,
            "counterHard": 0,
            "counterTooHard": 3,
            "counterExHard": 0,
            "counterBrainFuck": 2,
        },
        "avatar": "/storage/avatars/4aee57cc02f0181b22f4ccd43775f7ac.png",
        "difficultyText": "Easy",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": True,
        "maker": {
            "id": 550483,
            "name": "h4rithd",
            "avatar": "/storage/avatars/fbdcb50407810e387030e8c598fd033d.png",
            "isRespected": False,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.11.148",
    },
]
GET_MACHINES_DATA_RETIRED = [
    {
        "id": 1,
        "name": "Lame",
        "os": "Linux",
        "points": 0,
        "static_points": 20,
        "release": "2017-03-14T19:54:51.000000Z",
        "user_owns_count": 38208,
        "root_owns_count": 40570,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "4.4",
        "difficulty": 26,
        "feedbackForChart": {
            "counterCake": 22315,
            "counterVeryEasy": 15329,
            "counterEasy": 10215,
            "counterTooEasy": 3248,
            "counterMedium": 12669,
            "counterBitHard": 590,
            "counterHard": 347,
            "counterTooHard": 198,
            "counterExHard": 87,
            "counterBrainFuck": 215,
        },
        "avatar": "/storage/avatars/fb2d9f98400e3c802a0d7145e125c4ff.png",
        "difficultyText": "Easy",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": False,
        "maker": {
            "id": 1,
            "name": "ch4p",
            "avatar": "/storage/avatars/08c255a334e10b3033ab7263e6b32422.png",
            "isRespected": True,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.10.3",
        "tags": [
            {"id": 81, "tag_category_id": 11},
            {"id": 86, "tag_category_id": 11},
            {"id": 73, "tag_category_id": 6},
            {"id": 75, "tag_category_id": 7},
            {"id": 78, "tag_category_id": 9},
            {"id": 97, "tag_category_id": 11},
        ],
    },
    {
        "id": 2,
        "name": "Legacy",
        "os": "Windows",
        "points": 0,
        "static_points": 20,
        "release": "2017-03-14T22:45:38.000000Z",
        "user_owns_count": 28504,
        "root_owns_count": 29390,
        "authUserInUserOwns": True,
        "authUserInRootOwns": None,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "4.4",
        "difficulty": 25,
        "feedbackForChart": {
            "counterCake": 19597,
            "counterVeryEasy": 11152,
            "counterEasy": 6868,
            "counterTooEasy": 2247,
            "counterMedium": 8906,
            "counterBitHard": 391,
            "counterHard": 200,
            "counterTooHard": 96,
            "counterExHard": 64,
            "counterBrainFuck": 144,
        },
        "avatar": "/storage/avatars/60dc190c4c015cfe3a3aef9b5afca254.png",
        "difficultyText": "Easy",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": False,
        "maker": {
            "id": 1,
            "name": "ch4p",
            "avatar": "/storage/avatars/08c255a334e10b3033ab7263e6b32422.png",
            "isRespected": True,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.10.4",
        "tags": [{"id": 74, "tag_category_id": 6}, {"id": 81, "tag_category_id": 11}],
    },
    {
        "id": 3,
        "name": "Devel",
        "os": "Windows",
        "points": 0,
        "static_points": 20,
        "release": "2017-03-14T22:45:40.000000Z",
        "user_owns_count": 24503,
        "root_owns_count": 25583,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "4.3",
        "difficulty": 36,
        "feedbackForChart": {
            "counterCake": 3932,
            "counterVeryEasy": 6851,
            "counterEasy": 10517,
            "counterTooEasy": 6347,
            "counterMedium": 11705,
            "counterBitHard": 1233,
            "counterHard": 796,
            "counterTooHard": 370,
            "counterExHard": 95,
            "counterBrainFuck": 161,
        },
        "avatar": "/storage/avatars/0fb6455a29eb4f2682f04a780ce26cb1.png",
        "difficultyText": "Easy",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": False,
        "maker": {
            "id": 1,
            "name": "ch4p",
            "avatar": "/storage/avatars/08c255a334e10b3033ab7263e6b32422.png",
            "isRespected": True,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.10.5",
        "tags": [
            {"id": 74, "tag_category_id": 6},
            {"id": 93, "tag_category_id": 7},
            {"id": 94, "tag_category_id": 11},
        ],
    },
    {
        "id": 4,
        "name": "Popcorn",
        "os": "Linux",
        "points": 0,
        "static_points": 30,
        "release": "2017-03-14T22:45:42.000000Z",
        "user_owns_count": 9936,
        "root_owns_count": 9181,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "4.0",
        "difficulty": 42,
        "feedbackForChart": {
            "counterCake": 740,
            "counterVeryEasy": 1608,
            "counterEasy": 3344,
            "counterTooEasy": 2947,
            "counterMedium": 6186,
            "counterBitHard": 865,
            "counterHard": 591,
            "counterTooHard": 256,
            "counterExHard": 62,
            "counterBrainFuck": 106,
        },
        "avatar": "/storage/avatars/06ffcd9635c701b4b6667ae4c97cc7e5.png",
        "difficultyText": "Medium",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": False,
        "maker": {
            "id": 1,
            "name": "ch4p",
            "avatar": "/storage/avatars/08c255a334e10b3033ab7263e6b32422.png",
            "isRespected": True,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.10.6",
        "tags": [{"id": 78, "tag_category_id": 9}],
    },
    {
        "id": 5,
        "name": "Beep",
        "os": "Linux",
        "points": 0,
        "static_points": 20,
        "release": "2017-03-14T22:45:43.000000Z",
        "user_owns_count": 17511,
        "root_owns_count": 18308,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "4.3",
        "difficulty": 36,
        "feedbackForChart": {
            "counterCake": 3538,
            "counterVeryEasy": 4547,
            "counterEasy": 6735,
            "counterTooEasy": 4288,
            "counterMedium": 9348,
            "counterBitHard": 943,
            "counterHard": 613,
            "counterTooHard": 242,
            "counterExHard": 68,
            "counterBrainFuck": 139,
        },
        "avatar": "/storage/avatars/995f465295b99869fce21ecadea4604c.png",
        "difficultyText": "Easy",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": False,
        "maker": {
            "id": 1,
            "name": "ch4p",
            "avatar": "/storage/avatars/08c255a334e10b3033ab7263e6b32422.png",
            "isRespected": True,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.10.7",
        "tags": [{"id": 95, "tag_category_id": 11}],
    },
    {
        "id": 6,
        "name": "Optimum",
        "os": "Windows",
        "points": 0,
        "static_points": 20,
        "release": "2017-03-18T06:28:47.000000Z",
        "user_owns_count": 25292,
        "root_owns_count": 19802,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "4.5",
        "difficulty": 33,
        "feedbackForChart": {
            "counterCake": 8153,
            "counterVeryEasy": 7144,
            "counterEasy": 6795,
            "counterTooEasy": 3966,
            "counterMedium": 9510,
            "counterBitHard": 1172,
            "counterHard": 808,
            "counterTooHard": 431,
            "counterExHard": 112,
            "counterBrainFuck": 186,
        },
        "avatar": "/storage/avatars/bb09ffeaffe2f5220a1d591bb7b4f95e.png",
        "difficultyText": "Easy",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": False,
        "maker": {
            "id": 1,
            "name": "ch4p",
            "avatar": "/storage/avatars/08c255a334e10b3033ab7263e6b32422.png",
            "isRespected": True,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.10.8",
        "tags": [{"id": 74, "tag_category_id": 6}],
    },
    {
        "id": 7,
        "name": "Bastard",
        "os": "Windows",
        "points": 0,
        "static_points": 30,
        "release": "2017-03-18T20:19:32.000000Z",
        "user_owns_count": 8534,
        "root_owns_count": 7982,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "4.6",
        "difficulty": 44,
        "feedbackForChart": {
            "counterCake": 581,
            "counterVeryEasy": 1073,
            "counterEasy": 2269,
            "counterTooEasy": 2498,
            "counterMedium": 5285,
            "counterBitHard": 1034,
            "counterHard": 730,
            "counterTooHard": 361,
            "counterExHard": 113,
            "counterBrainFuck": 119,
        },
        "avatar": "/storage/avatars/a8d2ae87fbe6d1ccfe93522d74defb3a.png",
        "difficultyText": "Medium",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": False,
        "maker": {
            "id": 1,
            "name": "ch4p",
            "avatar": "/storage/avatars/08c255a334e10b3033ab7263e6b32422.png",
            "isRespected": True,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.10.9",
        "tags": [
            {"id": 74, "tag_category_id": 6},
            {"id": 78, "tag_category_id": 9},
            {"id": 99, "tag_category_id": 11},
        ],
    },
    {
        "id": 8,
        "name": "Tenten",
        "os": "Linux",
        "points": 0,
        "static_points": 30,
        "release": "2017-03-22T07:39:37.000000Z",
        "user_owns_count": 4280,
        "root_owns_count": 4338,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "3.3",
        "difficulty": 41,
        "feedbackForChart": {
            "counterCake": 912,
            "counterVeryEasy": 702,
            "counterEasy": 1062,
            "counterTooEasy": 1027,
            "counterMedium": 3034,
            "counterBitHard": 395,
            "counterHard": 325,
            "counterTooHard": 141,
            "counterExHard": 55,
            "counterBrainFuck": 75,
        },
        "avatar": "/storage/avatars/e58a465e93364c423cd2162945f8f7bf.png",
        "difficultyText": "Medium",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": False,
        "maker": {
            "id": 1,
            "name": "ch4p",
            "avatar": "/storage/avatars/08c255a334e10b3033ab7263e6b32422.png",
            "isRespected": True,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.10.10",
        "tags": [{"id": 78, "tag_category_id": 9}, {"id": 94, "tag_category_id": 11}],
    },
    {
        "id": 9,
        "name": "Arctic",
        "os": "Windows",
        "points": 0,
        "static_points": 20,
        "release": "2017-03-22T07:40:48.000000Z",
        "user_owns_count": 10245,
        "root_owns_count": 8934,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "2.2",
        "difficulty": 35,
        "feedbackForChart": {
            "counterCake": 1027,
            "counterVeryEasy": 1814,
            "counterEasy": 3737,
            "counterTooEasy": 2890,
            "counterMedium": 2,
            "counterBitHard": 793,
            "counterHard": 448,
            "counterTooHard": 201,
            "counterExHard": 67,
            "counterBrainFuck": 111,
        },
        "avatar": "/storage/avatars/0d6275efbd5e48fcdc96e61b9724ae5e.png",
        "difficultyText": "Easy",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": False,
        "maker": {
            "id": 1,
            "name": "ch4p",
            "avatar": "/storage/avatars/08c255a334e10b3033ab7263e6b32422.png",
            "isRespected": True,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.10.11",
        "tags": [
            {"id": 74, "tag_category_id": 6},
            {"id": 94, "tag_category_id": 11},
            {"id": 99, "tag_category_id": 11},
        ],
    },
    {
        "id": 11,
        "name": "Cronos",
        "os": "Linux",
        "points": 0,
        "static_points": 30,
        "release": "2017-03-22T14:57:21.000000Z",
        "user_owns_count": 9592,
        "root_owns_count": 8915,
        "authUserInUserOwns": True,
        "authUserInRootOwns": True,
        "isTodo": False,
        "authUserHasReviewed": False,
        "stars": "4.5",
        "difficulty": 41,
        "feedbackForChart": {
            "counterCake": 867,
            "counterVeryEasy": 1523,
            "counterEasy": 3220,
            "counterTooEasy": 2910,
            "counterMedium": 5671,
            "counterBitHard": 899,
            "counterHard": 525,
            "counterTooHard": 201,
            "counterExHard": 55,
            "counterBrainFuck": 69,
        },
        "avatar": "/storage/avatars/f77c75f363afe0d0a6eeccf6a8d8c252.png",
        "difficultyText": "Medium",
        "playInfo": {
            "isSpawned": False,
            "isSpawning": None,
            "isActive": None,
            "active_player_count": None,
            "expires_at": None,
        },
        "free": False,
        "maker": {
            "id": 1,
            "name": "ch4p",
            "avatar": "/storage/avatars/08c255a334e10b3033ab7263e6b32422.png",
            "isRespected": True,
        },
        "maker2": None,
        "recommended": 0,
        "sp_flag": 0,
        "easy_month": 0,
        "ip": "10.10.10.13",
        "tags": [
            {"id": 78, "tag_category_id": 9},
            {"id": 83, "tag_category_id": 9},
            {"id": 102, "tag_category_id": 11},
            {"id": 101, "tag_category_id": 11},
        ],
    },
]
GET_TODO_MACHINES_IDS = [
    1,
    113,
    114,
    115,
    116,
    117,
    133,
    137,
    400,
    401,
    410,
    415,
    416,
    421,
    423,
    429,
    431,
    432,
    437,
    438,
    442,
]
GET_MACHINE_DATA_ACUTE = {
    "id": 438,
    "name": "Acute",
    "os": "Windows",
    "active": 1,
    "retired": 0,
    "ip": "10.10.11.145",
    "points": 40,
    "static_points": 40,
    "release": "2022-02-12T17:00:00.000000Z",
    "user_owns_count": 303,
    "root_owns_count": 255,
    "free": True,
    "authUserInUserOwns": None,
    "authUserInRootOwns": None,
    "authUserHasReviewed": False,
    "stars": "4.6",
    "difficulty": 63,
    "avatar": "/storage/avatars/84ab22908d5dd51ab6bd64f99f81b7be.png",
    "feedbackForChart": {
        "counterCake": 8,
        "counterVeryEasy": 3,
        "counterEasy": 3,
        "counterTooEasy": 12,
        "counterMedium": 73,
        "counterBitHard": 53,
        "counterHard": 77,
        "counterTooHard": 36,
        "counterExHard": 12,
        "counterBrainFuck": 18,
    },
    "difficultyText": "Hard",
    "isCompleted": False,
    "last_reset_time": None,
    "playInfo": {
        "isSpawned": True,
        "isSpawning": None,
        "isActive": True,
        "active_player_count": 1,
        "expires_at": "2022-03-03 16:11:54",
    },
    "maker": {
        "id": 610173,
        "name": "dmw0ng",
        "avatar": "/storage/avatars/629da08cdd36bcee3a3ae1506e88b41d.png",
        "isRespected": False,
    },
    "maker2": None,
    "authUserFirstUserTime": None,
    "authUserFirstRootTime": None,
    "userBlood": {
        "user": {
            "name": "xct",
            "id": 13569,
            "avatar": "/storage/avatars/8c9faea377de064aa1c5333355e4ac14.png",
        },
        "created_at": "2022-02-12 22:20:24",
        "blood_difference": "1H 20M 24S",
    },
    "userBloodAvatar": "/storage/avatars/8c9faea377de064aa1c5333355e4ac14.png",
    "rootBlood": {
        "user": {
            "name": "jazzpizazz",
            "id": 87804,
            "avatar": "/storage/avatars/f6bdebbfbf3ffadf14179eb9d84f052a.png",
        },
        "created_at": "2022-02-13 01:29:58",
        "blood_difference": "4H 29M 58S",
    },
    "rootBloodAvatar": "/storage/avatars/f6bdebbfbf3ffadf14179eb9d84f052a.png",
    "firstUserBloodTime": "1H 20M 24S",
    "firstRootBloodTime": "4H 29M 58S",
    "recommended": 0,
    "sp_flag": 0,
    "lab_server": "vip_lab",
}
GET_MACHINE_DATA_STEAMCLOUD = {
    "id": 443,
    "name": "SteamCloud",
    "os": "Linux",
    "active": 0,
    "retired": 1,
    "ip": "10.10.11.132",
    "points": 0,
    "static_points": 20,
    "release": "2022-02-14T08:00:05.000000Z",
    "user_owns_count": 337,
    "root_owns_count": 269,
    "free": True,
    "authUserInUserOwns": None,
    "authUserInRootOwns": None,
    "authUserHasReviewed": False,
    "stars": "4.9",
    "difficulty": 42,
    "avatar": "/storage/avatars/a1fbd7cce1df4145b6a95df4644321bf.png",
    "feedbackForChart": {
        "counterCake": 20,
        "counterVeryEasy": 29,
        "counterEasy": 90,
        "counterTooEasy": 85,
        "counterMedium": 87,
        "counterBitHard": 30,
        "counterHard": 16,
        "counterTooHard": 6,
        "counterExHard": 3,
        "counterBrainFuck": 6,
    },
    "difficultyText": "Easy",
    "isCompleted": False,
    "last_reset_time": None,
    "playInfo": {
        "isSpawned": False,
        "isSpawning": None,
        "isActive": None,
        "active_player_count": None,
        "expires_at": None,
    },
    "maker": {
        "id": 27390,
        "name": "felamos",
        "avatar": "/storage/avatars/758adb164c98bcee70f7d31329ab7233.png",
        "isRespected": False,
    },
    "maker2": None,
    "authUserFirstUserTime": None,
    "authUserFirstRootTime": None,
    "userBlood": {
        "user": {
            "name": "HTB-Bot",
            "id": 16,
            "avatar": "/storage/avatars/9177afe0c83dc47db062d0581891560b.png",
        },
        "created_at": "2022-02-14 10:00:05",
        "blood_difference": "2H 0M 0S",
    },
    "userBloodAvatar": "/storage/avatars/9177afe0c83dc47db062d0581891560b.png",
    "rootBlood": {
        "user": {
            "name": "HTB-Bot",
            "id": 16,
            "avatar": "/storage/avatars/9177afe0c83dc47db062d0581891560b.png",
        },
        "created_at": "2022-02-14 10:00:05",
        "blood_difference": "2H 0M 0S",
    },
    "rootBloodAvatar": "/storage/avatars/9177afe0c83dc47db062d0581891560b.png",
    "firstUserBloodTime": "2H 0M 0S",
    "firstRootBloodTime": "2H 0M 0S",
    "recommended": 0,
    "sp_flag": 0,
    "lab_server": None,
}
GET_MACHINE_DATA_ROUTERSPACE_RA = {
    "id": 444,
    "name": "RouterSpace",
    "os": "Linux",
    "active": 1,
    "retired": 0,
    "ip": "10.129.177.81",
    "points": 20,
    "static_points": 20,
    "release": "2022-02-26T17:00:00.000000Z",
    "user_owns_count": 262,
    "root_owns_count": 221,
    "free": True,
    "authUserInUserOwns": None,
    "authUserInRootOwns": None,
    "authUserHasReviewed": False,
    "stars": "2.7",
    "difficulty": 37,
    "avatar": "/storage/avatars/4aee57cc02f0181b22f4ccd43775f7ac.png",
    "feedbackForChart": {
        "counterCake": 12,
        "counterVeryEasy": 14,
        "counterEasy": 11,
        "counterTooEasy": 14,
        "counterMedium": 20,
        "counterBitHard": 2,
        "counterHard": 1,
        "counterTooHard": 3,
        "counterExHard": 0,
        "counterBrainFuck": 2,
    },
    "difficultyText": "Easy",
    "isCompleted": False,
    "last_reset_time": None,
    "playInfo": {
        "isSpawned": False,
        "isSpawning": None,
        "isActive": True,
        "active_player_count": None,
        "expires_at": None,
    },
    "maker": {
        "id": 550483,
        "name": "h4rithd",
        "avatar": "/storage/avatars/fbdcb50407810e387030e8c598fd033d.png",
        "isRespected": False,
    },
    "maker2": None,
    "authUserFirstUserTime": None,
    "authUserFirstRootTime": None,
    "userBlood": {
        "user": {
            "name": "szymex73",
            "id": 139466,
            "avatar": "/storage/avatars/e4bc1f843595a4f4654f328790237298.png",
        },
        "created_at": "2022-02-26 21:19:37",
        "blood_difference": "0H 19M 37S",
    },
    "userBloodAvatar": "/storage/avatars/e4bc1f843595a4f4654f328790237298.png",
    "rootBlood": {
        "user": {
            "name": "jkr",
            "id": 77141,
            "avatar": "/storage/avatars/ea81f81b11e714a38499f14923213694.png",
        },
        "created_at": "2022-02-26 21:37:02",
        "blood_difference": "0H 37M 2S",
    },
    "rootBloodAvatar": "/storage/avatars/ea81f81b11e714a38499f14923213694.png",
    "firstUserBloodTime": "0H 19M 37S",
    "firstRootBloodTime": "0H 37M 2S",
    "recommended": 0,
    "sp_flag": 0,
    "lab_server": "ra_lab",
}
GET_CURRENT_VPN_SERVER_DATA = {
    "lab": {
        "can_access": True,
        "location_type_friendly": "US - VIP",
        "assigned_server": {
            "id": 29,
            "friendly_name": "US VIP 7",
            "current_clients": 8,
            "location": "US",
        },
    },
    "starting_point": {
        "can_access": True,
        "location_type_friendly": "US - Starting Point VIP",
        "assigned_server": {
            "id": 415,
            "friendly_name": "US StartingPoint VIP 1",
            "current_clients": 44,
            "location": "US",
        },
    },
    "endgames": {
        "can_access": True,
        "location_type_friendly": "EU - Endgame",
        "assigned_server": {
            "id": 37,
            "friendly_name": "EU Endgame 1",
            "current_clients": 1,
            "location": "EU",
        },
    },
    "fortresses": {
        "can_access": True,
        "location_type_friendly": "US - Fortress",
        "assigned_server": {
            "id": 19,
            "friendly_name": "US Fortress 1",
            "current_clients": 7,
            "location": "US",
        },
    },
    "pro_labs": {"can_access": False, "assigned_server": None},
    "release_arena": {
        "can_access": True,
        "assigned_server": {
            "id": 267,
            "friendly_name": "EU Release Lab 1",
            "current_clients": 75,
            "location": "EU",
        },
        "available": True,
        "location_type_friendly": "EU - Release Arena",
        "machine": {
            "id": 444,
            "name": "RouterSpace",
            "avatar_thumb_url": "https://www.hackthebox.com/storage/avatars/4aee57cc02f0181b22f4ccd43775f7ac_thumb.png",
        },
    },
}
GET_ALL_RA_VPN_SERVER_DATA = {
    "EU": {
        "EU - Release Arena": {
            "location": "EU",
            "name": "EU - Release Arena",
            "servers": {
                "267": {
                    "id": 267,
                    "friendly_name": "EU Release Lab 1",
                    "current_clients": 36,
                    "location": "EU",
                }
            },
        }
    },
    "US": {
        "US - Release Arena": {
            "location": "US",
            "name": "US - Release Arena",
            "servers": {
                "268": {
                    "id": 268,
                    "friendly_name": "US Release Lab 1",
                    "current_clients": 27,
                    "location": "US",
                }
            },
        }
    },
}
GET_ALL_VPN_SERVER_DATA = {
    "EU": {
        "EU - Free": {
            "location": "EU",
            "name": "EU - Free",
            "servers": {
                "1": {
                    "id": 1,
                    "friendly_name": "EU Free 1",
                    "current_clients": 59,
                    "location": "EU",
                },
                "201": {
                    "id": 201,
                    "friendly_name": "EU Free 2",
                    "current_clients": 48,
                    "location": "EU",
                },
                "253": {
                    "id": 253,
                    "friendly_name": "EU Free 3",
                    "current_clients": 36,
                    "location": "EU",
                },
            },
        },
        "EU - VIP": {
            "location": "EU",
            "name": "EU - VIP",
            "servers": {
                "2": {
                    "id": 2,
                    "friendly_name": "EU VIP 1",
                    "current_clients": 18,
                    "location": "EU",
                },
                "5": {
                    "id": 5,
                    "friendly_name": "EU VIP 2",
                    "current_clients": 5,
                    "location": "EU",
                },
                "6": {
                    "id": 6,
                    "friendly_name": "EU VIP 3",
                    "current_clients": 5,
                    "location": "EU",
                },
                "7": {
                    "id": 7,
                    "friendly_name": "EU VIP 4",
                    "current_clients": 5,
                    "location": "EU",
                },
                "8": {
                    "id": 8,
                    "friendly_name": "EU VIP 5",
                    "current_clients": 8,
                    "location": "EU",
                },
                "9": {
                    "id": 9,
                    "friendly_name": "EU VIP 6",
                    "current_clients": 4,
                    "location": "EU",
                },
                "18": {
                    "id": 18,
                    "friendly_name": "EU VIP 7",
                    "current_clients": 2,
                    "location": "EU",
                },
                "21": {
                    "id": 21,
                    "friendly_name": "EU VIP 8",
                    "current_clients": 5,
                    "location": "EU",
                },
                "28": {
                    "id": 28,
                    "friendly_name": "EU VIP 9",
                    "current_clients": 2,
                    "location": "EU",
                },
                "30": {
                    "id": 30,
                    "friendly_name": "EU VIP 10",
                    "current_clients": 5,
                    "location": "EU",
                },
                "33": {
                    "id": 33,
                    "friendly_name": "EU VIP 11",
                    "current_clients": 5,
                    "location": "EU",
                },
                "36": {
                    "id": 36,
                    "friendly_name": "EU VIP 12",
                    "current_clients": 4,
                    "location": "EU",
                },
                "42": {
                    "id": 42,
                    "friendly_name": "EU VIP 13",
                    "current_clients": 2,
                    "location": "EU",
                },
                "44": {
                    "id": 44,
                    "friendly_name": "EU VIP 14",
                    "current_clients": 4,
                    "location": "EU",
                },
                "47": {
                    "id": 47,
                    "friendly_name": "EU VIP 15",
                    "current_clients": 4,
                    "location": "EU",
                },
                "49": {
                    "id": 49,
                    "friendly_name": "EU VIP 16",
                    "current_clients": 8,
                    "location": "EU",
                },
                "51": {
                    "id": 51,
                    "friendly_name": "EU VIP 17",
                    "current_clients": 2,
                    "location": "EU",
                },
                "54": {
                    "id": 54,
                    "friendly_name": "EU VIP 18",
                    "current_clients": 3,
                    "location": "EU",
                },
                "57": {
                    "id": 57,
                    "friendly_name": "EU VIP 19",
                    "current_clients": 5,
                    "location": "EU",
                },
                "61": {
                    "id": 61,
                    "friendly_name": "EU VIP 20",
                    "current_clients": 4,
                    "location": "EU",
                },
                "66": {
                    "id": 66,
                    "friendly_name": "EU VIP 21",
                    "current_clients": 3,
                    "location": "EU",
                },
                "68": {
                    "id": 68,
                    "friendly_name": "EU VIP 22",
                    "current_clients": 4,
                    "location": "EU",
                },
                "70": {
                    "id": 70,
                    "friendly_name": "EU VIP 23",
                    "current_clients": 2,
                    "location": "EU",
                },
                "73": {
                    "id": 73,
                    "friendly_name": "EU VIP 24",
                    "current_clients": 4,
                    "location": "EU",
                },
                "77": {
                    "id": 77,
                    "friendly_name": "EU VIP 25",
                    "current_clients": 3,
                    "location": "EU",
                },
                "122": {
                    "id": 122,
                    "friendly_name": "EU VIP 28",
                    "current_clients": 3,
                    "location": "EU",
                },
                "219": {
                    "id": 219,
                    "friendly_name": "EU VIP 26",
                    "current_clients": 3,
                    "location": "EU",
                },
                "222": {
                    "id": 222,
                    "friendly_name": "EU VIP 27",
                    "current_clients": 4,
                    "location": "EU",
                },
            },
        },
        "EU - VIP+": {
            "location": "EU",
            "name": "EU - VIP+",
            "servers": {
                "288": {
                    "id": 288,
                    "friendly_name": "EU VIP+ 1",
                    "current_clients": 37,
                    "location": "EU",
                },
                "314": {
                    "id": 314,
                    "friendly_name": "EU VIP+ 2",
                    "current_clients": 23,
                    "location": "EU",
                },
            },
        },
    },
    "US": {
        "US - Free": {
            "location": "US",
            "name": "US - Free",
            "servers": {
                "113": {
                    "id": 113,
                    "friendly_name": "US Free 1",
                    "current_clients": 59,
                    "location": "US",
                },
                "202": {
                    "id": 202,
                    "friendly_name": "US Free 2",
                    "current_clients": 63,
                    "location": "US",
                },
                "254": {
                    "id": 254,
                    "friendly_name": "US Free 3",
                    "current_clients": 59,
                    "location": "US",
                },
            },
        },
        "US - VIP": {
            "location": "US",
            "name": "US - VIP",
            "servers": {
                "11": {
                    "id": 11,
                    "friendly_name": "US VIP 1",
                    "current_clients": 26,
                    "location": "US",
                },
                "14": {
                    "id": 14,
                    "friendly_name": "US VIP 2",
                    "current_clients": 17,
                    "location": "US",
                },
                "17": {
                    "id": 17,
                    "friendly_name": "US VIP 3",
                    "current_clients": 7,
                    "location": "US",
                },
                "20": {
                    "id": 20,
                    "friendly_name": "US VIP 4",
                    "current_clients": 6,
                    "location": "US",
                },
                "23": {
                    "id": 23,
                    "friendly_name": "US VIP 5",
                    "current_clients": 7,
                    "location": "US",
                },
                "27": {
                    "id": 27,
                    "friendly_name": "US VIP 6",
                    "current_clients": 7,
                    "location": "US",
                },
                "29": {
                    "id": 29,
                    "friendly_name": "US VIP 7",
                    "current_clients": 7,
                    "location": "US",
                },
                "31": {
                    "id": 31,
                    "friendly_name": "US VIP 8",
                    "current_clients": 7,
                    "location": "US",
                },
                "35": {
                    "id": 35,
                    "friendly_name": "US VIP 9",
                    "current_clients": 6,
                    "location": "US",
                },
                "38": {
                    "id": 38,
                    "friendly_name": "US VIP 10",
                    "current_clients": 3,
                    "location": "US",
                },
                "41": {
                    "id": 41,
                    "friendly_name": "US VIP 11",
                    "current_clients": 8,
                    "location": "US",
                },
                "45": {
                    "id": 45,
                    "friendly_name": "US VIP 12",
                    "current_clients": 6,
                    "location": "US",
                },
                "46": {
                    "id": 46,
                    "friendly_name": "US VIP 13",
                    "current_clients": 4,
                    "location": "US",
                },
                "48": {
                    "id": 48,
                    "friendly_name": "US VIP 14",
                    "current_clients": 5,
                    "location": "US",
                },
                "50": {
                    "id": 50,
                    "friendly_name": "US VIP 15",
                    "current_clients": 4,
                    "location": "US",
                },
                "52": {
                    "id": 52,
                    "friendly_name": "US VIP 16",
                    "current_clients": 4,
                    "location": "US",
                },
                "56": {
                    "id": 56,
                    "friendly_name": "US VIP 17",
                    "current_clients": 4,
                    "location": "US",
                },
                "58": {
                    "id": 58,
                    "friendly_name": "US VIP 18",
                    "current_clients": 7,
                    "location": "US",
                },
                "65": {
                    "id": 65,
                    "friendly_name": "US VIP 19",
                    "current_clients": 9,
                    "location": "US",
                },
                "67": {
                    "id": 67,
                    "friendly_name": "US VIP 20",
                    "current_clients": 3,
                    "location": "US",
                },
                "69": {
                    "id": 69,
                    "friendly_name": "US VIP 21",
                    "current_clients": 3,
                    "location": "US",
                },
                "71": {
                    "id": 71,
                    "friendly_name": "US VIP 22",
                    "current_clients": 8,
                    "location": "US",
                },
                "74": {
                    "id": 74,
                    "friendly_name": "US VIP 23",
                    "current_clients": 5,
                    "location": "US",
                },
                "86": {
                    "id": 86,
                    "friendly_name": "US VIP 24",
                    "current_clients": 7,
                    "location": "US",
                },
                "89": {
                    "id": 89,
                    "friendly_name": "US VIP 25",
                    "current_clients": 4,
                    "location": "US",
                },
                "220": {
                    "id": 220,
                    "friendly_name": "US VIP 26",
                    "current_clients": 6,
                    "location": "US",
                },
                "223": {
                    "id": 223,
                    "friendly_name": "US VIP 27",
                    "current_clients": 6,
                    "location": "US",
                },
            },
        },
        "US - VIP+": {
            "location": "US",
            "name": "US - VIP+",
            "servers": {
                "289": {
                    "id": 289,
                    "friendly_name": "US VIP+ 1",
                    "current_clients": 71,
                    "location": "US",
                }
            },
        },
    },
    "AU": {
        "AU - Free": {
            "location": "AU",
            "name": "AU - Free",
            "servers": {
                "177": {
                    "id": 177,
                    "friendly_name": "AU Free 1",
                    "current_clients": 18,
                    "location": "AU",
                }
            },
        },
        "AU - VIP": {
            "location": "AU",
            "name": "AU - VIP",
            "servers": {
                "182": {
                    "id": 182,
                    "friendly_name": "AU VIP 1",
                    "current_clients": 15,
                    "location": "AU",
                }
            },
        },
    },
    "SG": {
        "SG - Free": {
            "location": "SG",
            "name": "SG - Free",
            "servers": {
                "251": {
                    "id": 251,
                    "friendly_name": "SG Free 1",
                    "current_clients": 16,
                    "location": "SG",
                }
            },
        },
        "SG - VIP": {
            "location": "SG",
            "name": "SG - VIP",
            "servers": {
                "252": {
                    "id": 252,
                    "friendly_name": "SG VIP 1",
                    "current_clients": 10,
                    "location": "SG",
                },
                "280": {
                    "id": 280,
                    "friendly_name": "SG VIP 2",
                    "current_clients": 14,
                    "location": "SG",
                },
            },
        },
    },
}
SEARCH_OXDF = {
    "challenges": [
        {
            "id": 106,
            "challenge_category_id": 4,
            "description": "I missed my flag",
            "value": "You know 0xDiablos",
        }
    ],
    "teams": [
        {
            "id": 946,
            "motto": None,
            "avatar": "c8c41c4a18675a74e01c8a20e8a0f662.jpg",
            "value": "0xDEADBEEF",
        },
        {
            "id": 538,
            "motto": None,
            "avatar": "7bcdf75ad237b8e02e301f4091fb6bc8.jpg",
            "value": "0xD0A",
        },
    ],
    "users": [
        {"id": 4935, "avatar": "89c7e91c9f4b43a7ccedd10bbcc33fdc.png", "value": "0xdf"},
        {"id": 4935, "avatar": "89c7e91c9f4b43a7ccedd10bbcc33fdc.png", "value": "0xdf"},
        {
            "id": 214124,
            "avatar": "d6b50cbe91b87a90db75459e815eba90.png",
            "value": "0xdfbot",
        },
    ],
}
CONTENT_0xDF = {}
USER_0xdf = {
    "profile": {
        "id": 4935,
        "sso_id": None,
        "name": "0xdf",
        "system_owns": 251,
        "user_owns": 251,
        "user_bloods": 0,
        "system_bloods": 0,
        "team": None,
        "respects": 1766,
        "rank": "Omniscient",
        "rank_id": 7,
        "current_rank_progress": 0,
        "next_rank": None,
        "next_rank_points": None,
        "rank_ownership": 0,
        "rank_requirement": None,
        "ranking": None,
        "avatar": "/storage/avatars/89c7e91c9f4b43a7ccedd10bbcc33fdc.png",
        "timezone": "UTC",
        "isVip": False,
        "isDedicatedVip": True,
        "public": True,
        "country_name": "United States",
        "country_code": "US",
        "points": 389,
        "university": None,
        "university_name": None,
        "description": None,
        "github": "https://github.com/0xdf0xdf",
        "linkedin": None,
        "twitter": "https://twitter.com/0xdf_",
        "website": "https://0xdf.gitlab.io",
        "server": "US VIP 7",
    }
}
