name: Run Tests

on:
  pull_request:
    branches: [ master ]
    paths:
    -  'htbcli/*'
    -  'tests/*'
  push:
    branches: [ master ]
    paths:
    -  'htbcli/*'
    -  'tests/*'
  workflow_dispatch: {}


jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests and generate coverage report

        run: |
          python3 -m pytest -n auto --cov=htbcli --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          path_to_write_report: ./codecov_report.gz
